# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from arm_gazebo/angles.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class angles(genpy.Message):
  _md5sum = "1806b3e2a144e1ddd7c5a2029efd77fc"
  _type = "arm_gazebo/angles"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 chassis_arm1_joint
float32 arm1_arm2_joint
float32 arm2_arm3_joint 
float32 arm3_arm4_joint
"""
  __slots__ = ['chassis_arm1_joint','arm1_arm2_joint','arm2_arm3_joint','arm3_arm4_joint']
  _slot_types = ['float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       chassis_arm1_joint,arm1_arm2_joint,arm2_arm3_joint,arm3_arm4_joint

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(angles, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.chassis_arm1_joint is None:
        self.chassis_arm1_joint = 0.
      if self.arm1_arm2_joint is None:
        self.arm1_arm2_joint = 0.
      if self.arm2_arm3_joint is None:
        self.arm2_arm3_joint = 0.
      if self.arm3_arm4_joint is None:
        self.arm3_arm4_joint = 0.
    else:
      self.chassis_arm1_joint = 0.
      self.arm1_arm2_joint = 0.
      self.arm2_arm3_joint = 0.
      self.arm3_arm4_joint = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4f().pack(_x.chassis_arm1_joint, _x.arm1_arm2_joint, _x.arm2_arm3_joint, _x.arm3_arm4_joint))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.chassis_arm1_joint, _x.arm1_arm2_joint, _x.arm2_arm3_joint, _x.arm3_arm4_joint,) = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4f().pack(_x.chassis_arm1_joint, _x.arm1_arm2_joint, _x.arm2_arm3_joint, _x.arm3_arm4_joint))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.chassis_arm1_joint, _x.arm1_arm2_joint, _x.arm2_arm3_joint, _x.arm3_arm4_joint,) = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4f = None
def _get_struct_4f():
    global _struct_4f
    if _struct_4f is None:
        _struct_4f = struct.Struct("<4f")
    return _struct_4f
